# Generated by Django 5.1 on 2024-08-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetingforms',
            name='columns_list',
            field=models.TextField(null=True),
        ),
    ]
