# Generated by Django 5.1 on 2024-08-17 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_tpmcsvdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvdata',
            options={'verbose_name': 'CP CSV Data', 'verbose_name_plural': 'CP CSV Data'},
        ),
        migrations.AddField(
            model_name='sample',
            name='cp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.csvdata'),
        ),
        migrations.AddField(
            model_name='sample',
            name='remarks',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
