# Generated by Django 5.1 on 2024-08-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_tpmcsvdata__id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
