# Generated by Django 5.1 on 2024-08-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_modaprojects_modauser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvdata',
            options={'verbose_name': 'CP Data', 'verbose_name_plural': 'CP Data'},
        ),
        migrations.AlterModelOptions(
            name='modaprojects',
            options={'verbose_name': 'Moda Project', 'verbose_name_plural': 'Moda Projects'},
        ),
        migrations.AlterModelOptions(
            name='modauser',
            options={'verbose_name': 'Moda User', 'verbose_name_plural': 'Moda Users'},
        ),
        migrations.AlterModelOptions(
            name='targetingforms',
            options={'verbose_name': 'Targeting Form', 'verbose_name_plural': 'Targeting Forms'},
        ),
        migrations.AlterModelOptions(
            name='tpmcsvdata',
            options={'verbose_name': 'TPM Data', 'verbose_name_plural': 'TPM Data'},
        ),
        migrations.AddField(
            model_name='modaprojects',
            name='area_office',
            field=models.CharField(choices=[('FAO', 'FAO'), ('HAO', 'HAO'), ('JAO', 'JAO'), ('KAO', 'KAO'), ('KANAO', 'KANAO'), ('MAO', 'MAO')], max_length=5, null=True),
        ),
    ]
