# Generated by Django 5.1 on 2024-08-17 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_csvdata_options_alter_modaprojects_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CP_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(default='cp', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('label_english', models.CharField(max_length=255)),
                ('label_dari', models.CharField(max_length=255)),
                ('label_pashto', models.CharField(max_length=255)),
                ('ao', models.CharField(choices=[('FAO', 'FAO'), ('HAO', 'HAO'), ('JAO', 'JAO'), ('KAO', 'KAO'), ('KANAO', 'KANAO'), ('MAO', 'MAO')], max_length=5)),
                ('status', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'CP List',
                'verbose_name_plural': 'CP List',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(default='district', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('label_english', models.CharField(max_length=255)),
                ('label_dari', models.CharField(max_length=255)),
                ('label_pashto', models.CharField(max_length=255)),
                ('ao', models.CharField(choices=[('FAO', 'FAO'), ('HAO', 'HAO'), ('JAO', 'JAO'), ('KAO', 'KAO'), ('KANAO', 'KANAO'), ('MAO', 'MAO')], max_length=5)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(default='province', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('label_dari', models.CharField(max_length=255)),
                ('label_pashto', models.CharField(max_length=255)),
                ('ao', models.CharField(choices=[('FAO', 'FAO'), ('HAO', 'HAO'), ('JAO', 'JAO'), ('KAO', 'KAO'), ('KANAO', 'KANAO'), ('MAO', 'MAO')], max_length=5)),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='TPM_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(default='tpm_org', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('label_english', models.CharField(max_length=255)),
                ('label_dari', models.CharField(max_length=255)),
                ('label_pashto', models.CharField(max_length=255)),
                ('ao', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255, null=True)),
                ('province', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'TPM List',
                'verbose_name_plural': 'TPM List',
            },
        ),
        migrations.CreateModel(
            name='VillageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(default='village_list', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('cfac_code', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('province_code', models.CharField(max_length=255)),
                ('district_code', models.CharField(max_length=255)),
                ('cfac_name', models.CharField(max_length=255)),
                ('ao', models.CharField(choices=[('FAO', 'FAO'), ('HAO', 'HAO'), ('JAO', 'JAO'), ('KAO', 'KAO'), ('KANAO', 'KANAO'), ('MAO', 'MAO')], max_length=5)),
            ],
            options={
                'verbose_name': 'Village List',
                'verbose_name_plural': 'Village Lists',
            },
        ),
        migrations.CreateModel(
            name='CFACList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(default='cfac_list', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('ao', models.CharField(choices=[('FAO', 'FAO'), ('HAO', 'HAO'), ('JAO', 'JAO'), ('KAO', 'KAO'), ('KANAO', 'KANAO'), ('MAO', 'MAO')], max_length=5)),
                ('province', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('CFAC_FP1', models.CharField(max_length=255)),
                ('FP1_Number', models.CharField(max_length=255)),
                ('CFAC_FP2', models.CharField(max_length=255)),
                ('FP2_Number', models.CharField(max_length=255)),
                ('Province_code', models.CharField(max_length=255)),
                ('District_code', models.CharField(max_length=255)),
                ('CFAC_Name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CFAC List',
                'verbose_name_plural': 'CFAC List',
            },
        ),
    ]
