# Generated by Django 5.1 on 2024-08-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_cp_list_district_province_tpm_list_villagelist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='tpmcsvdata',
            name='ben_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
