# Generated by Django 5.1 on 2024-08-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_csvdata__id_alter_tpmcsvdata_ben_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpmcsvdata',
            name='ben_id',
            field=models.IntegerField(unique=True),
        ),
    ]
