# Generated by Django 5.1 on 2024-08-18 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_tpmcsvdata_ben_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmcsvdata',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tpm_records', to='base.sample'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Borderline', 'Borderline')], max_length=20),
        ),
    ]
