# Generated by Django 5.1 on 2024-08-22 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_approvedlist_moda_id_alter_approvedlist_ben_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvedlist',
            old_name='ben_id',
            new_name='cp_id',
        ),
        migrations.RemoveField(
            model_name='cfaclist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cfaclist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cfaclist',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='modaprojects',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='modaprojects',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='modaprojects',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='modauser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='modauser',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='modauser',
            name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='cp_list',
            unique_together={('name', 'ao')},
        ),
        migrations.AlterUniqueTogether(
            name='tpm_list',
            unique_together={('name', 'ao')},
        ),
    ]
