# Generated by Django 5.1 on 2024-09-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_cpdatamodel1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpdatamodel',
            name='SB_nahia',
            field=models.IntegerField(null=True),
        ),
    ]
