# Generated by Django 5.1 on 2024-09-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_cpdatamodel1_sb_nahia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpdatamodel1',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='cpdatamodel1',
            name='pbw_num',
            field=models.IntegerField(null=True),
        ),
    ]
