# Generated by Django 5.1 on 2024-09-29 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_cpdatamodel1_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpdatamodel1',
            old_name='district',
            new_name='SB_district',
        ),
        migrations.RenameField(
            model_name='cpdatamodel1',
            old_name='province',
            new_name='SB_province',
        ),
    ]
