# Generated by Django 5.1 on 2024-09-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_rename_district_cpdatamodel1_sb_district_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpdatamodel1',
            options={'verbose_name': 'CP Data', 'verbose_name_plural': 'CP Data'},
        ),
        migrations.AlterModelOptions(
            name='csvdata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tpmdatamodel',
            options={'verbose_name': 'TPM Data', 'verbose_name_plural': 'TPM Data'},
        ),
        migrations.AlterField(
            model_name='cpdatamodel1',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
