# Generated by Django 5.1 on 2024-09-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_cpdatamodel1_options_alter_csvdata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpdatamodel1',
            name='p_id_doc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
