# Generated by Django 5.1 on 2024-09-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_cpdatamodel1_p_id_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpdatamodel1',
            name='ass_modality',
            field=models.IntegerField(choices=[(1, 'FOOD'), (2, 'CBT')]),
        ),
    ]
