# Generated by Django 5.1 on 2024-09-29 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_cpdatamodel1_ass_modality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_urban', models.BooleanField()),
                ('ben_id', models.IntegerField(unique=True)),
                ('sample_type', models.CharField(choices=[('Regular', 'Regular'), ('Borderline', 'Borderline')], max_length=20)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.cpdatamodel1')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
