# Generated by Django 5.1 on 2024-09-29 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_sample1_options_alter_sample1_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample1',
            name='key',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sample1',
            name='cp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.cpdatamodel1'),
        ),
    ]
