# Generated by Django 5.1 on 2024-10-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_media_files_mediafilestype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetingforms',
            name='moda_media_files',
            field=models.ManyToManyField(to='base.mediafilestype'),
        ),
    ]
