# Generated by Django 5.1 on 2024-10-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_tpm_ee_data_tpm_sc_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpm_sc_data',
            name='SubmissionDate',
            field=models.DateTimeField(null=True),
        ),
    ]
