# Generated by Django 5.1 on 2024-10-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_tpm_sc_data_submissiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpm_sc_data',
            name='SB_area',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
