# Generated by Django 5.1 on 2024-10-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_tpm_sc_data_sb_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpm_ee_data',
            name='ag_work',
        ),
        migrations.RemoveField(
            model_name='tpm_ee_data',
            name='ass_modality',
        ),
        migrations.RemoveField(
            model_name='tpm_ee_data',
            name='is_principal',
        ),
        migrations.RemoveField(
            model_name='tpm_ee_data',
            name='name_p',
        ),
        migrations.RemoveField(
            model_name='tpm_ee_data',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='tpm_ee_data',
            name='p_age',
        ),
        migrations.RemoveField(
            model_name='tpm_ee_data',
            name='p_fath',
        ),
        migrations.RemoveField(
            model_name='tpm_ee_data',
            name='p_gender',
        ),
        migrations.RemoveField(
            model_name='tpm_ee_data',
            name='p_id_doc',
        ),
        migrations.RemoveField(
            model_name='tpm_ee_data',
            name='p_id_doc_other',
        ),
        migrations.RemoveField(
            model_name='tpm_ee_data',
            name='p_id_number',
        ),
        migrations.RemoveField(
            model_name='tpm_ee_data',
            name='p_mob',
        ),
    ]
