# Generated by Django 5.1 on 2024-10-07 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_tpm_sc_data_sample'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_key', models.CharField(max_length=50, unique=True)),
                ('tpm_vul', models.CharField(max_length=10, null=True)),
                ('tpm_hh_found', models.BooleanField(null=True)),
                ('status', models.CharField(max_length=255)),
                ('final_comment', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bs', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='final_approval', to='base.cpdatamodel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aproved List',
                'verbose_name_plural': 'Aproved List',
            },
        ),
    ]
