# Generated by Django 5.1 on 2024-10-08 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_finalapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalapproval',
            name='bs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='final_approval', to='base.cpdatamodel1'),
        ),
    ]
