# Generated by Django 5.1 on 2024-10-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_alter_finalapproval_bs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpdatamodel1',
            name='CFAC_Calculation',
            field=models.IntegerField(null=True),
        ),
    ]
